# Generated by Django 6.0.3 on 2026-03-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('score_correct', models.IntegerField(default=0)),
                ('score_total', models.IntegerField(default=0)),
                ('quiz_scores', models.JSONField(default=dict)),
                ('quiz_history', models.JSONField(default=list)),
                ('reverse_scores', models.JSONField(default=dict)),
                ('reverse_history', models.JSONField(default=list)),
                ('mixed_scores', models.JSONField(default=dict)),
                ('mixed_history', models.JSONField(default=list)),
                ('con_scores', models.JSONField(default=dict)),
                ('con_history', models.JSONField(default=list)),
                ('theme', models.CharField(default='dark', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
