# Generated by Django 6.0.3 on 2026-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='custom_words',
            field=models.JSONField(default=dict),
        ),
    ]
