# Generated by Django 6.0.3 on 2026-03-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_quizstate_custom_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='dyslexia_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizstate',
            name='tutorial_seen',
            field=models.BooleanField(default=False),
        ),
    ]
