# Generated by Django 6.0.3 on 2026-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_quizstate_dyslexia_font_quizstate_tutorial_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstate',
            name='theme',
            field=models.CharField(default='dark', max_length=20),
        ),
    ]
