# Generated by Django 6.0.3 on 2026-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_quizstate_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='activity_log',
            field=models.JSONField(default=dict),
        ),
    ]
