# Generated by Django 6.0.3 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_quizstate_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstate',
            name='con_guesses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizstate',
            name='mixed_guesses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizstate',
            name='quiz_guesses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quizstate',
            name='reverse_guesses',
            field=models.JSONField(default=list),
        ),
    ]
